image: node:19

#before_script:
  #- npm install

cache:
  paths:
    - node_modules/

pages:
  before_script:
    # Clean public folder
    - find public -mindepth 1 -maxdepth 1 -type d | xargs rm -rf
    - find public -type f -name "*.html" | xargs rm -rf
    - npm install
  script:
    - npm run build
    - mv build/* public
    # - npm tailwindcss -o .public/styles.css --minify
  after_script:
    - rm -rf build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
